export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE"; 
export const GET_LANG_TABLE = "GET_LANG_TABLE";
export const LANG_REQUEST_FAILURE = "LANG_REQUEST_FAILURE";
export const STORE_MESSAGES = "STORE_MESSAGES"
export const LANG_INFO = "LANG_INFO"
export const CLEAR_LANG_DATA = "CLEAR_LANG_DATA"
export const LANG_CHANGE_ACTIVITY = "LANG_CHANGE_ACTIVITY" 

export const LOGOUT = "LOGOUT"
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_SUCCESS_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const STORE_TREE = "STORE_TREE";


export const NETWORK_ERROR = "NETWORK_ERROR";
export const CLOSE_NETWORK_ERROR = "CLOSE_NETWORK_ERROR";

export const CURRENT_SCREEN = "CURRENT_SCREEN";




