export const flagsinitState = {
  fields: {
    flag_code: {
      fieldType: "input",
      type: "text",
      label: "flag_code",
      validation: {
        length: 30,
      },
      validity: {
        valid: true,
        touched: false,
        message: null,
      },
      writability: true,
      value: "",
      fKTable: {
        SPN: "label_code",
        PN: "flag_code",
      },
      readOnlyField: "label_code_m",
      readOnlyFieldT: "label_code",
      controlField: true,
      rowStyle: {
        backgroundColor: "#f8f9fa",
      },
      fillFields: [
        { recordName: "label_code", stateName: "label_code_m" },
        { recordName: "flag_code", stateName: "flag_code" },
      ],
    },
    label_code_m: {
      fieldType: "input",
      type: "text",
      label: "label_code",
      readOnly: true,
      writability: false,
      value: "",
      autoFilledSuccess: false,
      controlField: true,
      backgroundColor: "green",
    },
    holder1: { fieldType: "holder" },
    holder2: { fieldType: "holder" },
    flag_value: {
      fieldType: "input",
      type: "number",
      label: "flag_value",
      validation: {
        requiered: true,
        length: 30,
      },
      validity: {
        valid: true,
        touched: false,
        message: null,
      },
      writability: false,
      value: "",
    },
    label_code: {
      fieldType: "input",
      type: "text",
      label: "label_code",
      validation: {
        requiered: true,
        length: 100,
      },
      validity: {
        valid: true,
        touched: false,
        message: null,
      },
      writability: true,
      value: "",
    },
    flag_sr: {
      fieldType: "input",
      type: "number",
      label: "flag_sr",
      validation: {
        requiered: true,
        length: 200,
      },
      validity: {
        valid: true,
        touched: false,
        message: null,
      },
      writability: false,
      value: "",
    },
    flag_priv: {
      fieldType: "checkbox",
      type: "checkbox",
      label: "flag_priv",
      writability: false,
      value: false,
    },
    active: {
      fieldType: "checkbox",
      type: "checkbox",
      label: "active",
      writability: false,
      value: false,
    },
  },
  pks: ["flag_value"],
  urls: {
    add: "flagDetail",
    modify: "flagDetail",
    search: "flagDetail",
    pages: "flagDetail/pages",
    page: "flagDetail/page",
    lastPage: "flagDetail/lastPage",
    filter: "flagDetail/filteredPages",
    pageNo: "flagDetail/pageNo",
    delete: "flagDetail",
  },
  fks: ["flag_code"],
  fkList: {
    flag_code: {
      mainFields: ["flag_code", "label_code"],
      urls: {
        add: "flagMaster",
        modify: "flagMaster",
        search: "flagMaster",
        pages: "flagMaster/pages",
        page: "flagMaster/page",
        lastPage: "flagMaster/lastPage",
        filter: "flagMaster/filteredPages",
        pageNo: "flagMaster/pageNo",
        delete: "flagMaster",
      },
    },
  },

  mainFields: ["flag_value", "label_code"],
  tapName: "labels",
  searchFields: ["flag_value"],
}